import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const source = (relative: string) => readFileSync(new URL(relative, import.meta.url), 'utf8')

test('workspace sidebar keeps fixed top and footer around one scroll area', () => {
  const menu = source('./menu.vue')
  assert.ok(menu.indexOf('class="logo_row"') < menu.indexOf('class="menu_top"'))
  assert.ok(menu.indexOf('class="menu_top"') < menu.indexOf('class="menu_bottom"'))
  assert.match(menu, /min-width: 250px;\s*width: 250px/)
  assert.match(menu, /&--collapsed \{[\s\S]*?min-width: 60px;\s*width: 60px/)
  assert.match(menu, /<BrandLogo class="logo" portal-lockup\s*\/>/)
  assert.match(menu, /\.logo_row \{[\s\S]*?background: transparent/)
  assert.match(menu, /border-bottom: 1px solid var\(--td-component-stroke\)/)
  assert.match(menu, /:deep\(\.brand-logo__mark\)/)
})

test('sidebar IA distinguishes Portal home, current space, and space-scoped resources', () => {
  const navigation = source('../config/navigation.ts')
  const zh = source('../i18n/locales/zh-CN.ts')
  const en = source('../i18n/locales/en-US.ts')
  const switcher = source('./SpaceSwitcher.vue')
  const adminSwitcher = source('./TenantSelector.vue')
  assert.match(zh, /portalHome: '首页'/)
  assert.doesNotMatch(zh, /portalHome: '知识门户'/)
  assert.match(zh, /knowledgeBases: '空间知识库'/)
  assert.match(zh, /members: '空间成员'/)
  assert.match(en, /knowledgeBases: 'Space Knowledge Bases'/)
  assert.match(en, /members: 'Space Members'/)
  assert.match(navigation, /id: 'knowledge-bases'[\s\S]*route: '\/platform\/knowledge-bases'/)
  assert.match(navigation, /id: 'knowledge-bases'[\s\S]*icon: 'knowledge-base'/)
  assert.match(switcher, /authStore\.currentTenantName/)
  assert.match(switcher, /spaceSwitcher\.currentSpace/)
  assert.match(switcher, /switchWorkspaceAndNavigate/)
  assert.match(switcher, /const canSwitch = computed\(\(\) => memberships\.value\.length > 1\)/)
  assert.match(switcher, /v-if="canSwitch" name="chevron-down"/)
  assert.match(switcher, /v-if="open && canSwitch"/)
  assert.match(adminSwitcher, /spaceSwitcher\.currentSpace/)
  const sidebar = source('./SidebarNavigation.vue')
  assert.match(sidebar, /v-if="group\.id === 'global' && authStore\.effectiveTenantId" class="nav-group space-context"/)
  assert.ok(
    sidebar.indexOf("group.id === 'global' && authStore.effectiveTenantId") < sidebar.indexOf('<section class="nav-group">'),
    'current-space context should render before the Home navigation group',
  )
  assert.match(sidebar, /TenantSelector v-if="authStore\.canAccessAllTenants && !collapsed"/)
  assert.match(sidebar, /SpaceSwitcher v-else-if="!collapsed"/)
  assert.match(sidebar, /entry\.id === 'knowledge-bases'[\s\S]*nav-entry__knowledge-icon/)
  assert.match(sidebar, /zhishiku\.svg/)
  assert.doesNotMatch(sidebar, /currentTenantRole[^\n]*(SpaceSwitcher|TenantSelector)|(SpaceSwitcher|TenantSelector)[^\n]*currentTenantRole/)
})

test('Portal browsing is visual-only while Enter uses the shared current-space workflow', () => {
  const home = source('../views/portal/PortalHome.vue')
  const map = source('./portal/IpdKnowledgeMap.vue')
  const tenantSwitch = source('../utils/tenantSwitch.ts')
  const membersApi = source('../api/tenant/members.ts')
  assert.match(home, /function enterPortalSpace\(space:PortalSpace\)/)
  assert.match(home, /switchWorkspaceAndNavigate\(\{tenantId:space\.tenant_id,tenantName:space\.display_name/)
  assert.match(tenantSwitch, /authStore\.setSelectedTenant\(target\.tenantId, target\.tenantName\)/)
  assert.doesNotMatch(map, /setSelectedTenant|switchWorkspaceAndNavigate/)
  assert.match(map, /highlightedStageKey\.value=stageKey/)
  assert.match(membersApi, /\/api\/v1\/tenants\/\$\{tenantId\}\/members/)
})

test('active space switching uses one knowledge-base landing without widening tenant scope', () => {
  const switcher = source('./SpaceSwitcher.vue')
  const tenantSelector = source('./TenantSelector.vue')
  const switchFlow = source('../utils/tenantSwitch.ts')
  const policy = source('../utils/tenantSwitchPolicy.ts')
  const navigation = source('../config/navigation.ts')
  const portal = source('../views/portal/PortalHome.vue')
  assert.match(switcher, /const memberships = computed\(\(\) => authStore\.memberships \|\| \[\]\)/)
  assert.match(switcher, /v-for="membership in filtered"/)
  assert.match(switcher, /if \(isCurrent\(membership\.tenant_id\)\)/)
  assert.doesNotMatch(switcher + tenantSelector, /window\.location|router\.(?:push|replace)/)
  assert.match(switcher, /switchWorkspaceAndNavigate/)
  assert.match(tenantSelector, /switchWorkspaceAndNavigate/)
  assert.match(switchFlow, /navigateAfterTenantSwitch\(target\.targetPath\)/)
  assert.match(switchFlow, /restorePreviousTenant\(\)/)
  assert.match(switchFlow, /consumePendingTenantSwitchToast\(\)/)
  assert.match(switchFlow, /catch \{[\s\S]*restorePreviousTenant\(\)[\s\S]*target\.onNavigationFailure\?\.\(\)/)
  assert.match(policy, /TENANT_SWITCH_FALLBACK = '\/platform\/knowledge-bases'/)
  assert.doesNotMatch(policy, /TENANT_SWITCH_FALLBACK = '\/portal'/)
  assert.match(portal, /targetPath:'\/platform\/knowledge-bases'/)
  assert.match(navigation, /id: 'portal'[^\n]*route: '\/portal'/)
  assert.match(navigation, /id: 'knowledge-bases'[^\n]*route: '\/platform\/knowledge-bases'/)
})

test('agents are expanded by default and shortcuts come from the existing agent store', () => {
  const navigation = source('./SidebarNavigation.vue')
  assert.match(navigation, /knowhub\.sidebar\.agents\.expanded/)
  assert.match(navigation, /localStorage\.getItem\(AGENTS_EXPANDED_KEY\)!=='false'/)
  assert.match(navigation, /chatResources\.ensureAgents\(\)/)
  assert.match(navigation, /\[\.\.\.chatResources\.agents\][\s\S]*\.slice\(0,4\)/)
  assert.match(navigation, /v-for="agent in shortcutAgents"/)
  assert.doesNotMatch(navigation, /快速问答|智能推理|维基问答|数据分析师/)
})

test('agent shortcut reuses Agent Center run flow and cannot bypass disabled state', () => {
  const navigation = source('./SidebarNavigation.vue')
  const agentList = source('../views/agent/AgentList.vue')
  assert.match(navigation, /:disabled="isAgentDisabled\(agent\.id\)"/)
  assert.match(navigation, /if\(!isAgentDisabled\(agentId\)\)void router\.push\(\{path:'\/platform\/agents',query:\{runAgent:agentId\}\}\)/)
  assert.match(agentList, /const requestedId = typeof route\.query\.runAgent/)
  assert.match(agentList, /if \(agent\.disabled_by_me\)/)
  assert.match(agentList, /await startAgentChat\(agent\.id\)/)
  assert.match(navigation, /openAllAgents[\s\S]*router\.push\('\/platform\/agents'\)/)
  assert.doesNotMatch(navigation, /agent-shortcut--all/)
  assert.match(navigation, /class="agent-shortcuts__all" :title="t\('navigation\.allAgents'\)"/)
  assert.match(navigation, /:aria-label="t\('navigation\.allAgents'\)" @click="openAllAgents"/)
  assert.match(navigation, /class="agent-shortcuts__toggle"[\s\S]*@click="toggleAgents"/)
  assert.match(navigation, /v-if="entry\.id === 'agents' && !collapsed"/)
})

test('recent conversations default open, preserve API order, and show five until expanded', () => {
  const menu = source('./menu.vue')
  assert.match(menu, /const recentChatsExpanded = ref\(true\)/)
  assert.match(menu, /filteredGroupedSessions\.value\.flatMap\(\(group\) => group\.items\)/)
  assert.match(menu, /compacted\.slice\(0, 5\)/)
  assert.match(menu, /const isDefaultTitle = \(session: any\)/)
  assert.match(menu, /title === t\('menu\.newSession'\)/)
  assert.match(menu, /!isDefaultTitle\(session\).*?!isDefaultTitle\(sessions\[index - 1\]\)/s)
  assert.match(menu, /v-for="subitem in visibleRecentSessions"/)
  assert.match(menu, /subitem\.path === currentSecondpath/)
  assert.match(menu, /@navigate="gotopage\(subitem\.path\)"/)
  assert.match(menu, /if \(!showAllRecent\.value\) return/)
})

test('collapsed sidebar hides agent children and expands from the agent icon', () => {
  const navigation = source('./SidebarNavigation.vue')
  assert.match(navigation, /entry\.id === 'agents' && !collapsed/)
  assert.match(navigation, /entry\.id==='agents'&&props\.collapsed\)\{uiStore\.expandSidebar\(\);return\}/)
})

test('user footer displays account identity instead of repeating current space', () => {
  const userMenu = source('./UserMenu.vue')
  const info = userMenu.match(/<div class="user-info">([\s\S]*?)<\/div>\s*<t-icon/)?.[1] || ''
  assert.match(info, /\{\{ userName \}\}/)
  assert.match(info, /currentRoleLabel \|\| userEmail/)
  assert.doesNotMatch(info, /activeTenantName|user-tenant-name/)
})
