PRAGMA foreign_keys=OFF;
ALTER TABLE tenant_api_keys RENAME TO tenant_api_keys_pre_user_mcp;
CREATE TABLE tenant_api_keys (
 id INTEGER PRIMARY KEY AUTOINCREMENT, tenant_id INTEGER, owner_user_id TEXT,
 scope_type TEXT NOT NULL DEFAULT 'tenant' CHECK(scope_type IN('tenant','platform','user_mcp')),
 name TEXT NOT NULL,key_hash TEXT NOT NULL UNIQUE,api_key TEXT NOT NULL DEFAULT '',full_access BOOLEAN NOT NULL DEFAULT 0,
 knowledge_base_ids TEXT NOT NULL DEFAULT '[]',capabilities TEXT NOT NULL DEFAULT '[]',last_used_at DATETIME,expires_at DATETIME,revoked_at DATETIME,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE CASCADE,
 CHECK((scope_type='tenant' AND tenant_id IS NOT NULL AND owner_user_id IS NULL) OR(scope_type='platform' AND tenant_id IS NULL AND owner_user_id IS NULL AND full_access=0) OR(scope_type='user_mcp' AND tenant_id IS NULL AND owner_user_id IS NOT NULL AND full_access=0))
);
INSERT INTO tenant_api_keys(id,tenant_id,scope_type,name,key_hash,api_key,full_access,knowledge_base_ids,capabilities,last_used_at,expires_at,revoked_at,created_at,updated_at) SELECT id,tenant_id,scope_type,name,key_hash,api_key,full_access,knowledge_base_ids,capabilities,last_used_at,expires_at,revoked_at,created_at,updated_at FROM tenant_api_keys_pre_user_mcp;
DROP TABLE tenant_api_keys_pre_user_mcp;
CREATE INDEX idx_tenant_api_keys_tenant ON tenant_api_keys(tenant_id); CREATE INDEX idx_tenant_api_keys_revoked_at ON tenant_api_keys(revoked_at); CREATE INDEX idx_tenant_api_keys_scope_type ON tenant_api_keys(scope_type); CREATE INDEX idx_tenant_api_keys_owner_user ON tenant_api_keys(owner_user_id);
CREATE TABLE api_key_tenant_scopes(id INTEGER PRIMARY KEY AUTOINCREMENT,api_key_id INTEGER NOT NULL REFERENCES tenant_api_keys(id) ON DELETE CASCADE,tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,kb_scope_mode TEXT NOT NULL CHECK(kb_scope_mode IN('all','selected')),UNIQUE(api_key_id,tenant_id));
CREATE INDEX idx_api_key_tenant_scopes_tenant ON api_key_tenant_scopes(tenant_id);
CREATE TABLE api_key_kb_scopes(id INTEGER PRIMARY KEY AUTOINCREMENT,api_key_tenant_scope_id INTEGER NOT NULL REFERENCES api_key_tenant_scopes(id) ON DELETE CASCADE,api_key_id INTEGER NOT NULL REFERENCES tenant_api_keys(id) ON DELETE CASCADE,tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,knowledge_base_id TEXT NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,source_type TEXT NOT NULL CHECK(source_type IN('owned','shared')),kb_share_id TEXT REFERENCES kb_shares(id) ON DELETE CASCADE,CHECK((source_type='owned' AND kb_share_id IS NULL)OR(source_type='shared' AND kb_share_id IS NOT NULL)),UNIQUE(api_key_tenant_scope_id,knowledge_base_id,source_type));
CREATE INDEX idx_api_key_kb_scopes_lookup ON api_key_kb_scopes(api_key_id,tenant_id,knowledge_base_id);
CREATE TRIGGER validate_api_key_tenant_scope_insert BEFORE INSERT ON api_key_tenant_scopes BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM tenant_api_keys k WHERE k.id=NEW.api_key_id AND k.scope_type='user_mcp' AND k.owner_user_id IS NOT NULL) THEN RAISE(ABORT,'tenant scope must belong to a user_mcp key') END; END;
CREATE TRIGGER validate_api_key_tenant_scope_update BEFORE UPDATE ON api_key_tenant_scopes BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM tenant_api_keys k WHERE k.id=NEW.api_key_id AND k.scope_type='user_mcp' AND k.owner_user_id IS NOT NULL) THEN RAISE(ABORT,'tenant scope must belong to a user_mcp key') END; SELECT CASE WHEN NEW.kb_scope_mode='all' AND EXISTS(SELECT 1 FROM api_key_kb_scopes s WHERE s.api_key_tenant_scope_id=NEW.id) THEN RAISE(ABORT,'all KB scope cannot contain selected KB rows') END; END;
CREATE TRIGGER validate_api_key_kb_scope_insert BEFORE INSERT ON api_key_kb_scopes BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM api_key_tenant_scopes s WHERE s.id=NEW.api_key_tenant_scope_id AND s.api_key_id=NEW.api_key_id AND s.tenant_id=NEW.tenant_id AND s.kb_scope_mode='selected') THEN RAISE(ABORT,'KB scope must match a selected tenant scope') END; SELECT CASE WHEN NEW.source_type='owned' AND NOT EXISTS(SELECT 1 FROM knowledge_bases kb WHERE kb.id=NEW.knowledge_base_id AND kb.tenant_id=NEW.tenant_id AND kb.deleted_at IS NULL) THEN RAISE(ABORT,'owned KB must belong to the target tenant') END; SELECT CASE WHEN NEW.source_type='shared' AND NOT EXISTS(SELECT 1 FROM kb_shares ks JOIN organization_tenant_members otm ON otm.organization_id=ks.organization_id JOIN organizations o ON o.id=ks.organization_id AND o.deleted_at IS NULL WHERE ks.id=NEW.kb_share_id AND ks.knowledge_base_id=NEW.knowledge_base_id AND ks.deleted_at IS NULL AND otm.tenant_id=NEW.tenant_id) THEN RAISE(ABORT,'shared KB must use an active share for the target tenant') END; END;
CREATE TRIGGER validate_api_key_kb_scope_update BEFORE UPDATE ON api_key_kb_scopes BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM api_key_tenant_scopes s WHERE s.id=NEW.api_key_tenant_scope_id AND s.api_key_id=NEW.api_key_id AND s.tenant_id=NEW.tenant_id AND s.kb_scope_mode='selected') THEN RAISE(ABORT,'KB scope must match a selected tenant scope') END; SELECT CASE WHEN NEW.source_type='owned' AND NOT EXISTS(SELECT 1 FROM knowledge_bases kb WHERE kb.id=NEW.knowledge_base_id AND kb.tenant_id=NEW.tenant_id AND kb.deleted_at IS NULL) THEN RAISE(ABORT,'owned KB must belong to the target tenant') END; SELECT CASE WHEN NEW.source_type='shared' AND NOT EXISTS(SELECT 1 FROM kb_shares ks JOIN organization_tenant_members otm ON otm.organization_id=ks.organization_id JOIN organizations o ON o.id=ks.organization_id AND o.deleted_at IS NULL WHERE ks.id=NEW.kb_share_id AND ks.knowledge_base_id=NEW.knowledge_base_id AND ks.deleted_at IS NULL AND otm.tenant_id=NEW.tenant_id) THEN RAISE(ABORT,'shared KB must use an active share for the target tenant') END; END;
PRAGMA foreign_keys=ON;
