export const branding = {
  productName: 'KnowHub',
  productNameZh: 'CSBU研发知识库',
  tagline: 'Unified Knowledge Hub for R&D',
  taglineZh: '研发统一知识库',
  capabilityLine: 'Unified Search · AI Q&A · Knowledge Governance',
  capabilityLineZh: '统一检索 · 智能问答 · 知识治理',
  faviconPath: '/favicon.ico',
  logoMarkPath: '/brand/knowhub-mark.svg',
  logoMarkDarkPath: '/brand/knowhub-mark-dark.svg',
  logoMarkInversePath: '/brand/knowhub-mark-inverse.svg',
  websiteUrl: null as string | null,
  supportUrl: null as string | null,
  upstreamName: 'WeKnora',
  upstreamRepositoryUrl: 'https://github.com/Tencent/WeKnora',
} as const
