import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const source = (name: string) => readFileSync(new URL(name, import.meta.url), 'utf8')

test('knowledge map renders every API stage in the lifecycle rail and dense card grid', () => {
  const map = source('./IpdKnowledgeMap.vue')
  const stage = source('./IpdStageCard.vue')
  assert.match(map, /<nav v-else class="lifecycle-rail"/)
  assert.match(map, /v-for="\(stage,index\) in stages"/)
  assert.doesNotMatch(map, /:space-count=|:short-description=/)
  assert.match(map, /class="stage-card-grid"/)
  assert.match(map, /v-for="\(stage,index\) in stages"/)
  assert.match(map, /v-for="space in spacesFor\(stage\.key\)"/)
  assert.doesNotMatch(map, /activeStageSpaces|role="tabpanel"|class="stage-panel"/)
  assert.doesNotMatch(stage, /role="tab"|aria-selected/)
  assert.match(map, /class="ipd-map"/)
  assert.match(map, /border-radius:14px/)
})

test('insight remains visible with zero spaces and the rail is dynamically sized', () => {
  const map = source('./IpdKnowledgeMap.vue')
  assert.match(map, /v-for="\(stage,index\) in stages"/)
  assert.match(map, /v-if="spacesFor\(stage\.key\)\.length === 1"/)
  assert.match(map, /v-else-if="spacesFor\(stage\.key\)\.length > 1"/)
  assert.match(map, /v-else class="stage-empty"/)
  assert.match(map, /stage\.key === 'insight' \? 'compass'/)
  assert.match(map, /repeat\(\$\{Math\.max\(stages\.length, 1\)\}/)
  assert.doesNotMatch(map, /repeat\(7|item in 7|stages\.length === 7/)
})

test('rail activation scrolls to a stage group and highlights it without filtering', () => {
  const map = source('./IpdKnowledgeMap.vue')
  const stage = source('./IpdStageCard.vue')
  assert.match(stage, /@click="\$emit\('navigate', stage\.key\)"/)
  assert.match(stage, /<button type="button"/)
  assert.match(map, /function navigateToStage\(stageKey:string\)/)
  assert.match(map, /querySelector<HTMLElement>\(`\[data-stage-group=/)
  assert.match(map, /scrollIntoView\(\{behavior:'smooth',block:'center'\}\)/)
  assert.match(map, /highlightedStageKey\.value=stageKey/)
  assert.match(map, /highlightedStageKey === stage\.key/)
  assert.match(map, /setTimeout\(\(\)=>\{highlightedStageKey\.value='';focusedStageKey\.value=''\},800\)/)
  assert.doesNotMatch(map, /filter\([^\n]*focusedStageKey|filter\([^\n]*highlightedStageKey/)
  assert.doesNotMatch(map, /currentStageKey|:current=/)
  assert.doesNotMatch(stage, /aria-current|stage-step\.current/)
})

test('stage cards use empty, flattened single-space, and multi-space layouts', () => {
  const map = source('./IpdKnowledgeMap.vue')
  const summary = source('./SpaceSummary.vue')
  assert.match(map, /class="stage-card__number"/)
  assert.match(map, /String\(index \+ 1\)\.padStart\(2, '0'\)/)
  assert.match(map, /variant="compact"/)
  assert.match(map, /variant="flat"/)
  assert.match(map, /'stage-card--wide': spacesFor\(stage\.key\)\.length > 1/)
  assert.match(map, /:hide-title="sameNormalizedText\(stage\.name, spacesFor\(stage\.key\)\[0\]\.display_name\)"/)
  assert.match(map, /:suppress-description="sameNormalizedText\(stage\.description, spacesFor\(stage\.key\)\[0\]\.description\)"/)
  assert.doesNotMatch(map, /'stage-card--wide': stage\.key === 'development'/)
  assert.doesNotMatch(map, /:stage-name=/)
  assert.match(summary, /v-show="isActiveSpace"/)
  assert.match(summary, /\.space-summary\.current\{border-color:/)
  assert.match(summary, /\.space-summary\.current\{[^}]*background:/)
})

test('space summary separates accessible entry from discoverable dialog behavior', () => {
  const summary = source('./SpaceSummary.vue')
  const home = source('../../views/portal/PortalHome.vue')
  assert.match(summary, /if\(props\.space\.access_state === 'accessible'\)emit\('enter',props\.space\)/)
  assert.match(summary, /else emit\('restricted',props\.space\)/)
  assert.match(summary, /space\.knowledge_base_count/)
  assert.match(summary, /space\.file_count/)
  assert.match(home, /if\(space\.access_state!=='accessible'\)\{openAccessDialog\(space\);return\}/)
  assert.match(home, /switchWorkspaceAndNavigate/)
})

test('accessible cards expose always-visible ask/search icon labels and one primary entry', () => {
  const summary = source('./SpaceSummary.vue')
  assert.match(summary, /class="icon-actions"/)
  assert.match(summary, /class="enter-action"/)
  assert.match(summary, /@click="\$emit\('search', space\)"/)
  assert.match(summary, /@click="\$emit\('ask', space\)"/)
  assert.match(summary, /<t-tooltip :content="actionLabel\('search'\)"/)
  assert.match(summary, /:aria-label="actionLabel\('ask'\)"/)
  assert.match(summary, /:title="actionLabel\('ask'\)"/)
  assert.match(summary, /action==='search'\?'portalCard\.search':'portalCard\.ask'/)
  assert.match(summary, /<t-icon name="chat" \/><span>\{\{ actionLabel\('ask'\) \}\}<\/span>/)
  assert.match(summary, /<t-icon name="search" \/><span>\{\{ actionLabel\('search'\) \}\}<\/span>/)
  assert.match(summary, /\.icon-actions\{opacity:1;pointer-events:auto\}/)
  assert.doesNotMatch(summary, /\.icon-actions\{opacity:0|\.space-summary:hover \.icon-actions|@media\(pointer:coarse\)/)
  assert.match(summary, /class="space-icon"/)
  assert.match(summary, /accessible-actions\{[^}]*border-top:1px solid/)
})

test('space metadata uses configured description and responsible team with safe fallbacks', () => {
  const summary = source('./SpaceSummary.vue')
  assert.match(summary, /props\.space\?\.description\?\.trim\(\)/)
  assert.match(summary, /resolvePortalResponsibleTeam\(props\.space,t\('portalCard\.unconfigured'\)\)/)
  assert.match(summary, /portalCard\.noSpaceDescription/)
  assert.match(summary, /portalCard\.unconfigured/)
  assert.match(summary, /class="space-owner" :title="displayResponsible"/)
  assert.doesNotMatch(summary, /contact|creator|currentTenantName/)
  assert.match(summary, /:title="displayDescription"/)
})

test('single stage and child cards bind owner presentation to the intended space record', () => {
  const map = source('./IpdKnowledgeMap.vue')
  const summary = source('./SpaceSummary.vue')
  assert.match(map, /resolvePortalResponsibleTeam\(spacesFor\(stageKey\)\[0\],t\('portalCard\.unconfigured'\)\)/)
  assert.match(map, /v-if="spacesFor\(stage\.key\)\.length === 1" :content="stageOwner\(stage\.key\)"/)
  assert.match(map, /v-for="space in spacesFor\(stage\.key\)" :key="space\.tenant_id" :space="space" variant="compact"/)
  assert.match(summary, /v-if="!suppressResponsible" :content="displayResponsible"/)
  assert.doesNotMatch(map, /v-else[^>]*stage-card__owner/)
})

test('all single-space and empty stages share the same bottom-aligned layout contract', () => {
  const map = source('./IpdKnowledgeMap.vue')
  const summary = source('./SpaceSummary.vue')
  assert.match(map, /\.stage-card\{display:flex;box-sizing:border-box;height:100%;flex-direction:column\}/)
  assert.match(map, /\.stage-spaces--single,\.stage-empty\{flex:1\}/)
  assert.match(summary, /\.accessible-actions,[^}]+\{margin-top:auto\}/)
  assert.doesNotMatch(map, /stage\.key === ['"](?:design|testing)['"]/)
})

test('single and current stage hover activates one surface without a nested action ring', () => {
  const map = source('./IpdKnowledgeMap.vue')
  const summary = source('./SpaceSummary.vue')
  assert.match(map, /'stage-card--current': spacesFor\(stage\.key\)\.length === 1/)
  assert.match(map, /\.stage-card--current\{[^}]*border-color:[^}]*background:/)
  assert.match(summary, /\.space-summary:hover,\.space-summary:focus-within\{outline:0;outline-offset:0\}/)
  assert.match(summary, /\.space-summary\.flat\.current,\.space-summary\.flat\.current:hover\{background:transparent\}/)
  assert.match(summary, /\.accessible-actions button:focus-visible\{outline:2px solid/)
  assert.doesNotMatch(map, /stage\.key === ['"](?:design|testing)['"]/)
})

test('IPD header renders only the shared asset summary without changing aggregation', () => {
  const map = source('./IpdKnowledgeMap.vue')
  const template = map.slice(0, map.indexOf('<script setup'))
  assert.doesNotMatch(template, /portalMap\.stageCount|portalMap\.coverage|class="lifecycle-metric"|coverage-metric/)
  assert.match(map, /class="asset-metric"/)
  assert.match(map, /formatAssetSummary\(summary\.ipd, t, numberFormatter\)/)
  assert.match(map, /buildKnowledgeHierarchySummary\(props\.spaces,props\.stages\.map\(stage=>stage\.key\)\)/)
})

test('rail is navigation-only and single-stage ownership is shown once in the header', () => {
  const map = source('./IpdKnowledgeMap.vue')
  const stage = source('./IpdStageCard.vue')
  assert.match(stage, /String\(index \+ 1\)\.padStart\(2, '0'\)/)
  assert.match(stage, /\{\{ stage\.name \}\}/)
  assert.doesNotMatch(stage, /shortDescription|spaceCount|stageSpaceCount|<small>|<em>/)
  assert.match(map, /v-if="spacesFor\(stage\.key\)\.length === 1" :content="stageOwner\(stage\.key\)"/)
  assert.match(map, /class="stage-card__owner"><t-icon name="user"/)
  assert.match(map, /suppress-responsible/)
  assert.match(map, /portalMap\.stageSpaceCountCompact/)
  assert.match(map, /\.stage-card__owner\{[^}]*max-width:52%[^}]*text-overflow:ellipsis[^}]*white-space:nowrap/)
})

test('restricted cards show one state-aware CTA and always activate the gate', () => {
  const summary = source('./SpaceSummary.vue')
  assert.match(summary, /v-else class="restricted-action"/)
  assert.match(summary, /access_request_pending\?t\('portal\.pending'\)/)
  assert.match(summary, /can_request_access\?t\('portal\.requestAccess'\):t\('portalMap\.getAccess'\)/)
  assert.match(summary, /@keydown\.enter\.prevent="activate"/)
  assert.match(summary, /@keydown\.space\.prevent="activate"/)
  assert.doesNotMatch(summary, /portalMap\.permissionRequired|portalMap\.learnAccess/)
})

test('access dialog retains real request states and readable space context', () => {
  const dialog = source('./SpaceAccessDialog.vue')
  assert.match(dialog, /space\.access_request_pending/)
  assert.match(dialog, /space\.can_request_access/)
  assert.match(dialog, /portalMap\.accessDialog\.titleWithSpace/)
  assert.match(dialog, /stageLabel/)
  assert.match(dialog, /:disabled="submitting \|\| !valid"/)
  assert.doesNotMatch(dialog, /knowledge_bases|documents|approve|reject/i)
})

test('hidden spaces are absent from the Portal response contract', () => {
  const api = source('../../api/portal.ts')
  assert.match(api, /PortalAccessState = 'accessible' \| 'discoverable'/)
  assert.doesNotMatch(api, /PortalAccessState[^\n]*hidden/)
})
